//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDataClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTable
    {
        public int FoodId { get; set; }
        public Nullable<int> VenueId { get; set; }
        public string Type { get; set; }
        public string MealType { get; set; }
        public string DishType { get; set; }
        public Nullable<int> Cost { get; set; }
    }
}
